(() => {
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const $ = s => document.querySelector(s);
  const screens = { start:$('#startScreen'), pause:$('#pauseScreen'), over:$('#gameOverScreen') };
  const ui = { distance:$('#distance'), level:$('#level'), status:$('#powerStatus'), finalDistance:$('#finalDistance'), chart:$('#chartBars'), daily:$('#dailyBest'), best:$('#bestEver'), message:$('#crashMessage'), newBest:$('#newBest'), pause:$('#pauseButton'), mute:$('#muteButton'), leaderboard:$('#leaderboardList'), leaderboardState:$('#leaderboardState'), leaderboardJoin:$('#leaderboardJoin'), leaderboardName:$('#leaderboardName') };
  const supabaseUrl='https://ceygvkgpbejwpsrxpfhv.supabase.co', supabaseKey='sb_publishable_4PTSZDenaUzApvSxnM_XsQ_V8-meavl';
  const themes = [
    {name:'Sunrise', top:'#ffb6ae', bottom:'#ffe4b8', glow:'#fff4be'}, {name:'Daytime', top:'#91dcff', bottom:'#d5f7ff', glow:'#fff'},
    {name:'Sunset', top:'#9c9ce5', bottom:'#ffc08f', glow:'#ffdca1'}, {name:'Starlight', top:'#263d82', bottom:'#6f7ac1', glow:'#e3e8ff'}
  ];
  const outfits=[['Tennis ace','🎾','#d5f177'],['Football star','⚽','#8bd06c'],['Basketball pro','🏀','#ffae63'],['Baseball slugger','⚾','#f2f2f2'],['Golfer','⛳','#94d882'],['Skier','⛷️','#bce9ff'],['Surfer','🏄','#6ed4de'],['Boxer','🥊','#ef6a64'],['Fencer','🤺','#d7e0ef'],['Cyclist','🚴','#ffdc63'],['Runner','🏃','#fe8a88'],['Swimmer','🏊','#77d7f3'],['Ballerina','🩰','#ffc8dc'],['Rock star','🎸','#a47be7'],['DJ','🎧','#7f8ad9'],['Chef','👨‍🍳','#ffffff'],['Astronaut','👨‍🚀','#bfd4ee'],['Pirate','🏴‍☠️','#303f5f'],['Wizard','🧙','#7d67ca'],['Knight','🛡️','#b5c2d7'],['Ninja','🥷','#3c455c'],['Superhero','🦸','#ef747a'],['Detective','🕵️','#b59570'],['Firefighter','🧑‍🚒','#ed6861'],['Doctor','🩺','#dff5f4'],['Builder','👷','#f4be54'],['Cowboy','🤠','#c8874e'],['Clown','🤡','#ff8e8a'],['King','👑','#f4ca52'],['Queen','👸','#eeb7d9'],['Bee','🐝','#f8dd55'],['Butterfly','🦋','#ab89ee'],['Unicorn','🦄','#eda4db'],['Dragon','🐉','#85c88b'],['Dinosaur','🦖','#7fc698'],['Shark','🦈','#81b7da'],['Frog','🐸','#7fce8d'],['Panda','🐼','#dce3e8'],['Tiger','🐯','#f7ab5b'],['Lion','🦁','#e8b75d'],['Cow','🐮','#f3e9e4'],['Santa','🎅','#e95d60'],['Elf','🧝','#68ba8b'],['Robot','🤖','#a9c2d1'],['Alien','👽','#a2d880'],['Mushroom','🍄','#ef7e79'],['Flower','🌼','#f6d664'],['Rainbow','🌈','#b48cec'],['Cloud','☁️','#c5e8fb'],['Banana','🍌','#f3de52'],['Sushi','🍣','#f19b9d'],['Donut','🍩','#df91b6']];
  let dpr, W, H, running=false, paused=false, muted=localStorage.koopaRunMuted==='1', last=0, elapsed=0, level=1, distance=0, nextGate=0, theme=0, objects=[], particles=[], power=null, powerTime=0, meteorTimer=0, music=null, outfit=null, shake=0;
  const puff={x:0,y:0,vy:0,r:25,shield:0}; const gravity=900;
  const dayKey='koopaRunDay-'+new Date().toISOString().slice(0,10), bestKey='koopaRunBest';
  const runsKey='koopaRunRecentFlights', playerIdKey='koopaRunLeaderboardPlayerId', playerNameKey='koopaRunLeaderboardName';
  const getNum=k=>+localStorage.getItem(k)||0; function refreshScores(){ui.daily.textContent=getNum(dayKey)+'m';ui.best.textContent=getNum(bestKey)+'m'} refreshScores();
  function playerId(){let id=localStorage.getItem(playerIdKey);if(!id){id=crypto.randomUUID();localStorage.setItem(playerIdKey,id)}return id}
  async function leaderboardCall(name,args){const response=await fetch(supabaseUrl+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:supabaseKey,Authorization:'Bearer '+supabaseKey,'Content-Type':'application/json'},body:JSON.stringify(args)});if(!response.ok)throw new Error('Leaderboard unavailable');return response.json()}
  function escapeHtml(value){const box=document.createElement('span');box.textContent=value;return box.innerHTML}
  function showLeaderboard(rows){ui.leaderboard.innerHTML='';if(!rows.length){ui.leaderboard.innerHTML='<li class="leaderboard-empty">Be the first Koopa flyer!</li>';return}rows.forEach((row,index)=>{const item=document.createElement('li');item.innerHTML='<span>'+(index+1)+'.</span><span>'+escapeHtml(row.display_name)+'</span><b>'+row.best_distance+'m</b>';ui.leaderboard.appendChild(item)})}
  async function loadLeaderboard(){ui.leaderboardState.textContent='Loading…';try{const rows=await leaderboardCall('get_koopa_leaderboard',{p_limit:5});showLeaderboard(rows);ui.leaderboardState.textContent='Top flyers'}catch(e){ui.leaderboard.innerHTML='<li class="leaderboard-empty">World chart is getting ready.</li>';ui.leaderboardState.textContent='Offline'}}
  async function submitFlight(flight){const name=localStorage.getItem(playerNameKey);if(!name)return;ui.leaderboardState.textContent='Saving…';try{await leaderboardCall('submit_koopa_score',{p_player_id:playerId(),p_display_name:name,p_distance:flight});await loadLeaderboard()}catch(e){ui.leaderboardState.textContent='Try again later'}}
  function resize(){dpr=Math.min(devicePixelRatio||1,2); W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(!running){puff.x=W*.28;puff.y=H*.49;draw();}} addEventListener('resize',resize);resize();
  function sound(type){if(muted)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),g=a.createGain(),o=a.createOscillator();o.connect(g);g.connect(a.destination);o.type=type==='crash'?'sawtooth':'sine';const start=type==='star'?880:type==='pass'?430:type==='power'?520:350,end=type==='star'?1560:type==='crash'?90:type==='pass'?560:510;o.frequency.setValueAtTime(start,a.currentTime);o.frequency.exponentialRampToValueAtTime(end,a.currentTime+.13);g.gain.setValueAtTime(type==='star'?.09:.07,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.18);o.start();o.stop(a.currentTime+.19);if(type==='star'){const sparkle=a.createOscillator();sparkle.connect(g);sparkle.frequency.setValueAtTime(1320,a.currentTime+.06);sparkle.frequency.exponentialRampToValueAtTime(1760,a.currentTime+.15);sparkle.start(a.currentTime+.06);sparkle.stop(a.currentTime+.18)}}catch(e){} }
  function rnd(a,b){return a+Math.random()*(b-a)} function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()} function rr(x,y,w,h,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
  function start(){stopMusic();level=1;distance=0;elapsed=0;nextGate=0;theme=0;objects=[];particles=[];power=null;powerTime=0;meteorTimer=0;outfit=null;shake=0;puff.x=W*.28;puff.y=H*.48;puff.vy=0;puff.r=25;puff.shield=0;running=true;paused=false;ui.distance.textContent='0m';ui.level.textContent=1;ui.status.textContent='🛋️ Level 1 · Avoid the sofas';Object.values(screens).forEach(x=>x.classList.add('hidden'));ui.pause.textContent='Ⅱ'; last=performance.now();requestAnimationFrame(loop);flap();}
  function flap(){if(!running||paused)return;puff.vy=-310; burst(puff.x-18,puff.y,5,'#ffffff');sound('flap');}
  function makeGate(){const kind='sofa',tier=Math.min(level,6),gaps=[220,202,181,161,98,84],redline=level>=5,gap=Math.max(62,gaps[tier-1]-(redline?18:0)),cy=rnd(125,H-125),x=W+55;objects.push({type:'gate',kind,x,cy,gap,w:62,passed:false,phase:rnd(0,6)});if(Math.random()<.7)objects.push({type:'bone',x:x+75,y:cy+rnd(-gap*.23,gap*.23),r:12,phase:rnd(0,6)});if(distance>250&&Math.random()<.16)objects.push({type:'ball',x:x+122,y:cy+rnd(-gap*.18,gap*.18),r:15,phase:rnd(0,6)});if(distance>500&&Math.random()<.09)objects.push({type:'power',x:x+160,y:cy+rnd(-gap*.18,gap*.18),r:18,kind:['shield','slow','lightning','missile'][Math.floor(Math.random()*4)]});}
  function burst(x,y,n,c){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-100,100),vy:rnd(-120,70),life:rnd(.3,.8),max:1,r:rnd(2,5),c});}
  function stopMusic(){if(!music)return;try{clearInterval(music.timer);music.a.close()}catch(e){}music=null}
  function startMusic(kind){stopMusic();if(muted)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),g=a.createGain(),songs={shield:{notes:[261,329,392,329,293,349,440,392],type:'sine',step:360,gain:.07},slow:{notes:[147,175,220,196,175,147,131,147],type:'triangle',step:470,gain:.06},lightning:{notes:[440,660,880,660,523,784,1047,784],type:'sawtooth',step:180,gain:.035},missile:{notes:[196,247,294,392,294,247,220,330],type:'square',step:255,gain:.04}}[kind];g.gain.value=1;g.connect(a.destination);let index=0;const play=()=>{const o=a.createOscillator(),ng=a.createGain();o.type=songs.type;o.frequency.setValueAtTime(songs.notes[index++%songs.notes.length],a.currentTime);ng.gain.setValueAtTime(songs.gain,a.currentTime);ng.gain.exponentialRampToValueAtTime(.001,a.currentTime+songs.step/1000*.85);o.connect(ng);ng.connect(g);o.start();o.stop(a.currentTime+songs.step/1000*.9)};play();music={a,timer:setInterval(play,songs.step)}}catch(e){}}
  function setPower(k){power=k;powerTime=k==='shield'||k==='missile'?10:k==='slow'?7:5;if(k==='shield')puff.shield=powerTime;if(k==='lightning'||k==='missile')objects=objects.filter(o=>o.type!=='gate');const labels={shield:'🛡️ Shield · 10s total immunity',slow:'🐢 Slow motion',lightning:'⚡ Lightning · Fast couch-free dash!',missile:'🚀 Space mission · No couches!'};ui.status.textContent=labels[k];meteorTimer=.45;startMusic(k);sound('power');burst(puff.x,puff.y,26,k==='missile'?'#a9b8ff':k==='lightning'?'#fff08b':'#83e5ff');}
  function wearOutfit(){let next=outfits[Math.floor(Math.random()*outfits.length)];if(outfits.length>1&&outfit&&next[0]===outfit[0])next=outfits[(outfits.indexOf(next)+1)%outfits.length];outfit=next;ui.status.textContent='⚽ Koopa is now a '+outfit[0]+'!';burst(puff.x,puff.y,24,outfit[2]);sound('power');}
  function saveRun(){const runs=JSON.parse(localStorage.getItem(runsKey)||'[]');runs.push({distance:Math.floor(distance)});localStorage.setItem(runsKey,JSON.stringify(runs.slice(-8)));return runs.slice(-8)}
  function drawChart(runs){ui.chart.innerHTML='';const highest=Math.max(1,...runs.map(run=>run.distance));runs.forEach((run,index)=>{const bar=document.createElement('i');bar.className='chart-bar'+(index===runs.length-1?' latest':'');bar.style.height=Math.max(7,Math.round(run.distance/highest*38))+'px';bar.title=run.distance+'m';ui.chart.appendChild(bar)})}
  function crash(){running=false;stopMusic();sound('crash');shake=12;burst(puff.x,puff.y,28,'#fff');const flight=Math.floor(distance),oldDaily=getNum(dayKey),oldBest=getNum(bestKey),isBest=flight>oldBest;if(flight>oldDaily)localStorage.setItem(dayKey,flight);if(isBest)localStorage.setItem(bestKey,flight);ui.finalDistance.textContent=flight+'m';drawChart(saveRun());ui.newBest.classList.toggle('hidden',!isBest);ui.message.textContent=['That couch had places to be.','Koopa is regrouping.','A very enthusiastic sofa situation!','The couch wins this round.','Koopa found the express lane.'][Math.floor(Math.random()*5)];refreshScores();ui.leaderboardJoin.classList.toggle('hidden',!!localStorage.getItem(playerNameKey));loadLeaderboard();if(localStorage.getItem(playerNameKey))submitFlight(flight);setTimeout(()=>screens.over.classList.remove('hidden'),450);}
  function hit(o){return Math.abs(puff.x-o.x)<puff.r+(o.w||o.r||20) && Math.abs(puff.y-o.y)<puff.r+(o.r||45)}
  function update(dt){const scale=power==='slow'?.55:power==='lightning'?1.45:1;elapsed+=dt;const tier=Math.min(level,6),baseSpeeds=[150,174,200,228,330,365],gateSpacing=[285,260,238,216,164,146],redline=level>=5,speed=(baseSpeeds[tier-1]+Math.min(elapsed*1.2,27)+(redline?70:0))*scale;distance+=dt*speed*.32;const travelled=Math.floor(distance),nextLevel=Math.max(1,Math.floor(Math.max(0,travelled-1)/1000)+1);if(nextLevel>level){level=nextLevel;ui.level.textContent=level;theme=(theme+1)%themes.length;ui.status.textContent='⚡ Level '+level+' · Sofas move faster!';burst(W*.5,H*.35,38,'#fff2a8');sound('power')}ui.distance.textContent=travelled+'m';puff.vy+=gravity*dt;puff.y+=puff.vy*dt;if(puff.y<-30||puff.y>H+30)crash();nextGate-=dt*speed;if(nextGate<=0){if(power!=='lightning'&&power!=='missile')makeGate();nextGate=gateSpacing[tier-1]-(redline?24:0)}if(power==='missile'){meteorTimer-=dt;if(meteorTimer<=0){objects.push({type:'meteor',x:W+45,y:rnd(75,H-75),r:rnd(15,27),spin:rnd(0,6)});meteorTimer=rnd(.42,.72)}}if(powerTime>0){powerTime-=dt;if(powerTime<=0){const endedPower=power;power=null;puff.shield=0;stopMusic();if(endedPower==='missile')objects=objects.filter(o=>o.type!=='meteor');ui.status.textContent='🛋️ Level '+level+' · Avoid the sofas'}}
    objects.forEach(o=>{o.x-=dt*speed*(power==='lightning'?1.15:1);if(o.type==='gate'){const touchingSofa=Math.abs(puff.x-o.x)<puff.r+o.w/2&&Math.abs(puff.y-o.cy)>o.gap/2-puff.r;if(touchingSofa&&power!=='shield')crash();else if(!o.passed&&o.x<puff.x){o.passed=true;sound('pass')}}else if(o.type==='meteor'){if(hit(o)&&power!=='shield')crash()}else if(hit(o)){if(o.type==='bone'){burst(o.x,o.y,12,'#f5cf84');sound('star')}else if(o.type==='ball')wearOutfit();else setPower(o.kind);o.dead=true}});objects=objects.filter(o=>o.x>-100&&!o.dead);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=110*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt*35);}
  function sky(){if(power==='missile'){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#08123e');g.addColorStop(1,'#37205c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<34;i++){const x=(i*83+33)%W,y=(i*137+45)%H;circle(x,y,i%5===0?2:1,i%5===0?'#9fd7ff':'#ffffffbb')}return}const t=themes[theme],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,t.top);g.addColorStop(1,t.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);circle(W*.8,H*.16,50,t.glow+'99');for(let i=0;i<8;i++){let x=(i*97+40)%W,y=(i*151+80)%H;circle(x,y,2,theme===3?'#ffffffaa':'#ffffff66')} }
  function cloud(x,y,s,a=.55){ctx.globalAlpha=a;circle(x-s*.36,y,s*.28,'#fff');circle(x,y-s*.12,s*.38,'#fff');circle(x+s*.38,y,s*.24,'#fff');rr(x-s*.55,y,s*1.12,s*.3,s*.15,'#fff');ctx.globalAlpha=1}
  function drawGate(o){const top=o.cy-o.gap/2,bottom=o.cy+o.gap/2,sofa=y=>{rr(o.x-38,y-24,76,46,13,'#b87666');rr(o.x-43,y-15,9,35,5,'#86594f');rr(o.x+34,y-15,9,35,5,'#86594f');rr(o.x-31,y-21,62,27,10,'#d89a83');ctx.strokeStyle='#f4c6ae';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(o.x,y-7);ctx.lineTo(o.x,y+18);ctx.stroke();rr(o.x-30,y+21,12,6,3,'#765047');rr(o.x+18,y+21,12,6,3,'#765047')};for(let y=25;y<top+25;y+=52)sofa(y);for(let y=bottom+25;y<H+25;y+=52)sofa(y)}
  function bone(o){ctx.save();ctx.translate(o.x,o.y+Math.sin(elapsed*4+o.phase)*4);ctx.rotate(-.35);ctx.fillStyle='#fff2d5';circle(-14,-7,6,'#fff2d5');circle(-14,7,6,'#fff2d5');circle(14,-7,6,'#fff2d5');circle(14,7,6,'#fff2d5');rr(-15,-7,30,14,5,'#fff2d5');ctx.fillStyle='#e8cda0';ctx.fillRect(-7,-3,14,6);ctx.restore()}
  function ball(o){ctx.save();ctx.translate(o.x,o.y+Math.sin(elapsed*4+o.phase)*4);ctx.rotate(elapsed*4);circle(0,0,15,'#f4b653');ctx.strokeStyle='#8f643e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,10,.4,2.7);ctx.moveTo(-10,0);ctx.lineTo(10,0);ctx.stroke();ctx.restore()}
  function drawPower(o){const icons={shield:'🛡️',slow:'🐢',lightning:'⚡',bomb:'💣',missile:'🚀'};circle(o.x,o.y,19,'#ffffffdd');ctx.font='21px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icons[o.kind],o.x,o.y+1)}
  function drawMeteor(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(elapsed*3+o.spin);circle(0,0,o.r,'#83686c');circle(-o.r*.22,-o.r*.2,o.r*.25,'#514653');circle(o.r*.3,o.r*.22,o.r*.18,'#514653');ctx.fillStyle='#ffbc6c';ctx.beginPath();ctx.moveTo(o.r,0);ctx.lineTo(o.r+17,-8);ctx.lineTo(o.r+12,8);ctx.fill();ctx.restore()}
  function puffDraw(){ctx.save();ctx.translate(puff.x,puff.y);if(power==='lightning'){ctx.strokeStyle='#ffe56b';ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-75,0);ctx.lineTo(-29,0);ctx.stroke()}if(puff.shield>0){ctx.strokeStyle='#82e5ffcc';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.stroke()}if(power==='missile'){circle(0,0,35,'#eaf8ff');circle(0,0,29,'#8ed9ff');circle(0,0,25,'#213b68')}if(outfit){rr(-20,16,40,17,7,outfit[2]);ctx.font='18px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(outfit[1],0,-30)}ctx.fillStyle='#d98a50';ctx.beginPath();ctx.moveTo(-21,-13);ctx.lineTo(-17,-35);ctx.lineTo(-3,-22);ctx.arc(0,0,27,0,Math.PI*2);ctx.lineTo(4,-22);ctx.lineTo(18,-35);ctx.lineTo(22,-12);ctx.fill();ctx.fillStyle='#fff5de';ctx.beginPath();ctx.ellipse(0,9,16,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4c352e';ctx.beginPath();ctx.moveTo(-5,5);ctx.lineTo(5,5);ctx.lineTo(0,11);ctx.fill();circle(-10,-4,3,'#2e2930');circle(10,-4,3,'#2e2930');ctx.strokeStyle='#4c352e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(-6,12,6,0.1,1.25);ctx.arc(6,12,6,1.9,3.04);ctx.stroke();ctx.restore()}
  function draw(){sky();ctx.save();if(shake)ctx.translate(rnd(-shake,shake),rnd(-shake,shake));objects.forEach(o=>o.type==='gate'?drawGate(o):o.type==='bone'?bone(o):o.type==='ball'?ball(o):o.type==='meteor'?drawMeteor(o):drawPower(o));particles.forEach(p=>{ctx.globalAlpha=Math.min(1,p.life/p.max);circle(p.x,p.y,p.r,p.c)});ctx.globalAlpha=1;puffDraw();ctx.restore()}
  function loop(now){if(!running)return;let dt=Math.min(.035,(now-last)/1000);last=now;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
  function togglePause(){if(!running)return;paused=!paused;screens.pause.classList.toggle('hidden',!paused);ui.pause.textContent=paused?'▶':'Ⅱ';if(!paused){last=performance.now();requestAnimationFrame(loop)}}
  canvas.addEventListener('pointerdown',e=>{e.preventDefault();flap()});$('#startButton').onclick=start;screens.start.addEventListener('pointerdown',e=>{if(e.target===screens.start)start()});$('#restartButton').onclick=start;$('#resumeButton').onclick=togglePause;ui.pause.onclick=togglePause;ui.leaderboardJoin.onsubmit=e=>{e.preventDefault();const name=ui.leaderboardName.value.trim();if(!name)return;localStorage.setItem(playerNameKey,name);ui.leaderboardJoin.classList.add('hidden');submitFlight(Math.floor(distance))};$('#homeButton').onclick=()=>{screens.over.classList.add('hidden');screens.start.classList.remove('hidden');draw()};ui.mute.onclick=()=>{muted=!muted;localStorage.koopaRunMuted=muted?'1':'0';if(muted)stopMusic();else if(power)startMusic(power);ui.mute.textContent=muted?'♩':'♪';ui.mute.setAttribute('aria-pressed',muted)};ui.mute.textContent=muted?'♩':'♪';addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='ArrowUp')&&!e.repeat){e.preventDefault();flap()}if(e.code==='KeyP')togglePause()});
})();
